### ISSUE TITLE
Harassment directed at US west coast signatories of the letter

### ISSUE THREAD

**Issue by againer** [nadimkobeissi/appleprivacyletter#7845]
Just an FYI to anyone signing here: My GH security logs show that unknown parties have been trying to get into my GH account.  I typically have very little activity here on GH, so it seems like more than just a coincidence.  Perhaps the owners can consider presenting our names on `https://appleprivacyletter.com/` with a little more anonymity.

**Comment by nadimkobeissi** [comment]
I'm reticent to cause unwarranted concern or to flirt with conspiracy theory, but unfortunately there seems to be a pattern of harassment directed at some signatories of the letter.

Very oddly, every single person who's contacted me regarding this happens to be an American software engineer working in the West coast.

I have so far removed a handful of signatures due to people from the above demographic complaining about:

- Attempts to break into their GitHub account,
- Anonymous harassment via online accounts and social media with messages related to the letter,
- In one case, even a false complaint report submitted to their employer.

I have no idea what to do with this information, but there have now been enough reports for me to publicly disclose it, and I hope that folks who have better insight than I do on this matter will offer suggestions.

Thanks.
